export default {
  Button: {
    variants: {
      primary: {
        height: 12,
        px: 12,
        bg: 'brand.500',
        _hover: { background: 'brand.600' },
        _active: { background: 'brand.700' },
        _disabled: {
          background: 'brandDisabled.500',
        },
        py: 3,
        color: 'white',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
        borderRadius: '8px',
      },
      primaryCta: {
        height: 8,
        px: 6,
        bg: 'brand.500',
        _hover: { background: 'brand.600' },
        _active: { background: 'brand.700' },
        _disabled: {
          background: 'brandDisabled.500',
        },
        py: '6px',
        color: 'white',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
      },
      resubmit: {
        height: 12,
        px: 12,
        bg: '#F3F4F4',
        _hover: { background: '#F5F5F5', borderColor: '#122224', borderWidth: '2px' },
        _active: { background: '#F5F5F5' },
        py: 3,
        color: 'black',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
      },
      reject: {
        height: 12,
        px: 12,
        bg: 'white',
        _hover: { background: '#F5F5F5' },
        _active: { background: '#F5F5F5' },
        py: 3,
        color: 'red',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
        border: '1px solid red',
      },
      disconnect: {
        height: 12,
        px: 12,
        bg: 'white',
        _hover: { background: '#F5F5F5' },
        _active: { background: '#F5F5F5' },
        py: 3,
        color: 'grey',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
        border: '1px solid grey',
      },
      manageGrantTab: {
        margin: '10px',
        fontSize: '20px',
        padding: '15px',
        textAlign: 'center',
        textTransform: 'uppercase',
        backgroundSize: '200% auto',
        color: '#FFF',
        borderRadius: '10px',
        width: '200px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
        transition: 'all 0.3s cubic-bezier(.25,.8,.25,1)',
        cursor: 'pointer',
        display: 'inline-block',
        _hover: {
          boxShadow: '0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23)',
          margin: '8px 10px 12px',
          backgroundPosition: 'right center',
        },
        backgroundImage: 'linear-gradient(to right, #DD5E89 0%, #F7BB97 51%, #DD5E89 100%)',
      },
    },
  },
};
