name: Check PR health

on: [pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: npm i --legacy-peer-deps
    
    - name: Check linting
      run: npm run lint

    - name: Check build
      run: npm run build
